<?php

use Drupal\calendar\CalendarHelper;
use Drupal\Core\Link;

/**
 * Implements hook_form_alter()
 */
function custom_events_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  if ($form['#id'] == 'views-exposed-form-events-page-1') {
    $form['#attached']['library'][] = 'custom_events/custom_events.enable';
    $form['#attached']['library'][] = 'custom_events/custom_events.forms';
  }

  // Event dates use date_range, however calendars use a single date field. Therefore we have to populate a single date
  // field with the date_range field populated by the user in order to use the calendar!
  if ($form_id == 'node_events_form' || $form_id == 'node_events_edit_form') {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = '_custom_events_events_form_submit';
      }
    }
  }
}

// Events need to add the start date in its date_range field to the single date field
// that is compatible with the calendar module. Called from the form_alter hook in this module.
function _custom_events_events_form_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $values = $form_state->getValues();
  if ($date = $form_state->getValue('field_date')) {
    $node = Node::load($values['nid']);
    $node->set('field_calendar_date', $date[0]['value']->format('Y-m-d'));
    $node->save();
  }
}

/**
 * Create the calendar date box.
 */
function custom_events_preprocess_calendar_datebox(&$vars) {
  $date = $vars['date'];
  $view = $vars['view'];
  $vars['day'] = intval(substr($date, 8, 2));
  $full_date_arg = str_replace('-', '', $date);
  $day_url = CalendarHelper::getURLForGranularity($view, 'day', [$full_date_arg]);

  if ($day_url) {
    // $vars['link'] = \Drupal::l($vars['day'], $day_url);
    $vars['link'] = Link::fromTextAndUrl($vars['day'], $day_url)->toRenderable();
    $vars['link']['#attributes']['rel'] = $date;
  }
  else {
    $vars['link'] = $vars['day'];
  }

  $vars['granularity'] = $view->dateInfo->getGranularity();
  $vars['mini'] = !empty($view->styleInfo->isMini());
  if ($vars['mini']) {
    if (!empty($vars['selected'])) {
      $vars['class'] = 'mini-day-on';
    }
    else {
      $vars['class'] = 'mini-day-off';
    }
  }
  else {
    $vars['class'] = 'day';
  }
}
