custom_events.settings:
  type: config_object
  mapping:
    source_date_field:
      type: string
      label: 'Source date field'
    calendar_date_field:
      type: string
      label: 'Calendar date field'
